# Generated by Django 2.0.7 on 2018-07-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('cod_filial', models.IntegerField(blank=True, null=True)),
                ('cep', models.CharField(max_length=10)),
            ],
        ),
    ]
