# Generated by Django 2.0.7 on 2018-07-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20180728_0038'),
        ('lojas', '0002_auto_20180728_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='produtos',
            field=models.ManyToManyField(blank=True, null=True, to='produtos.Produto'),
        ),
    ]
