# Generated by Django 2.0.7 on 2018-07-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0003_loja_produtos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='cod_filial',
            field=models.IntegerField(unique=True),
        ),
    ]
